### PR TITLE
Add !!LUAU shortcut

### PR DESCRIPTION
**Pull request by zapacni**
As much as Lua in all caps is a thing, Luau in all caps is too. Right now what I have is just a rough draft, definitely feel it can be more original. Feel free to suggest new wording. I also think "LuaU" could get its own template as well, but not too sure how that can be done without breaking consistency (all shortcuts are in caps)

### CODE REVIEW

**Review by posatta — COMMENTED** [review]
Might be worth mentioning the Hawaiian term that shares its pronunciation

**Comment by FxllenCode** [comment]
Yes, good point @posatta. I usually refer to Roblox's fork of lua as Lua(U)/LuaU so people don't get it confused with the hawaiian term.

**Comment by posatta** [comment]
> 
> 
> Yes, good point @posatta. I usually refer to Roblox's fork of lua as Lua(U)/LuaU so people don't get it confused with the hawaiian term.

The name is based on the Hawaiian term, I'm pretty sure. I just mentioned it as a point of reference. I think linking to the Luau thread (or maybe the tweet saying it means nothing) instead of the Lua thread might also be good with a different fun fact.

**Review by posatta — APPROVED** [review]
Looks good

**Comment by zapacni** [comment]
> Looks good

yea lookin pretty bobux

**Pull request merged**
