### PR TITLE
Some basic QoL features

### PR DESCRIPTION
**Pull request by zapacni**
In this PR you will find some basic QoL features, ~~mainly support for flairing all trust levels~~ still WIP, not just TL1, and no longer needing to clear composer to type shortcut to generate template.

~~For the former, `flairNewMember.js` may need to be updated,~~ undid changes but I think @posatta is gonna take care of that.

### CODE REVIEW

**Review by posatta — APPROVED** [review]
The composer part works well and seems to be a good QOL feature. We might want to consider in the future how the template strings right now are a bit inconsistent (a mix of backticks, and quotes, some starting on the same line and some not, etc.)

**Review by FxllenCode — APPROVED** [review]
Looks good, I assume the soon-to-be deprecated TL3 and TL4 won't be flaired. Glad to not have to delete the pre-existing text now!

**Review by FxllenCode — CHANGES_REQUESTED** [review]
Just thought of this-- I don't think it's smart to flair regulars, I'm used to seeing the flair just for members, besides, Regulars are Regular, no flair needed. We want members to stand out.

**Comment by zapacni** [comment]
>I'm used to seeing the flair just for members, 

That is why regulars will be flaired as regular 😉 and this won't happen for a while yet

**Comment by FxllenCode** [comment]
> >I'm used to seeing the flair just for members, 
> 
> That is why regulars will be flaired as regular 😉 and this won't happen for a while yet

I think my point is, regulars don't need to be flaired because we don't need to give them extra attention-- it's a bit confusing to look and see regulars being flaired similarly to members. Why don't we check if people have Sage/Editor/TC badges and flair them?

**Comment by zapacni** [comment]
> I think my point is, regulars don't need to be flaired because we don't need to give them extra attention-- it's a bit confusing to look and see regulars being flaired similarly to members. 

Consistency :p 

> Why don't we check if people have Sage/Editor/TC badges and flair them?

there are plans to do this (cc @posatta)

**Pull request merged**
